feat(contrib/valkey-io): bump valkey-go and add SetOnInvalidations wrapper (#4657)
### What does this PR do?

Upgrade valkey-go to v1.0.74, which extends DedicatedClient with
SetOnInvalidations for client-side caching invalidations. Delegate the
new hook on the traced dedicated client so the wrapper still implements
the upstream interface.

### Motivation

We cannot bump the valkey lib in our project.
They added the `SetOnInvalidations` on the `DedicatedClient` interface
-
https://github.com/valkey-io/valkey-go/commit/26dc6e88692ec8c950549cbf2a679a32709bbd3a

It create issue on DataDog lib side because it does not match the
interface
```console
~/work/DataDog/dd-trace-go/contrib/valkey-io/valkey-go git:(main) ✗ $ go test ./...
go: downloading github.com/DataDog/datadog-go v3.2.0+incompatible
go: downloading google.golang.org/genproto v0.0.0-20251022142026-3a174f9686a8
# github.com/DataDog/dd-trace-go/contrib/valkey-io/valkey-go/v2 [github.com/DataDog/dd-trace-go/contrib/valkey-io/valkey-go/v2.test]
./valkey.go:129:13: cannot use &dedicatedClient{…} (value of type *dedicatedClient) as "github.com/valkey-io/valkey-go".DedicatedClient value in argument to fn: *dedicatedClient does not implement "github.com/valkey-io/valkey-go".DedicatedClient (missing method SetOnInvalidations)
./valkey.go:138:9: cannot use &dedicatedClient{…} (value of type *dedicatedClient) as "github.com/valkey-io/valkey-go".DedicatedClient value in return statement: *dedicatedClient does not implement "github.com/valkey-io/valkey-go".DedicatedClient (missing method SetOnInvalidations)
./valkey.go:165:29: cannot use (*dedicatedClient)(nil) (value of type *dedicatedClient) as "github.com/valkey-io/valkey-go".DedicatedClient value in variable declaration: *dedicatedClient does not implement "github.com/valkey-io/valkey-go".DedicatedClient (missing method SetOnInvalidations)
FAIL    github.com/DataDog/dd-trace-go/contrib/valkey-io/valkey-go/v2 [build failed]
FAIL
```

### Reviewer's Checklist

- [ ] Changed code has unit tests for its functionality at or near 100%
coverage.
- [ ] [System-Tests](https://github.com/DataDog/system-tests/) covering
this feature have been added and enabled with the va.b.c-dev version
tag.
- [ ] There is a benchmark for any new code, or changes to existing
code.
- [x] If this interacts with the agent in a new way, a system test has
been added.
- [x] New code is free of linting errors. You can check this by running
`make lint` locally.
- [x] New code doesn't break existing tests. You can check this by
running `make test` locally.
- [ ] Add an appropriate team label so this PR gets put in the right
place for the release notes.
- [x] All generated files are up to date. You can check this by running
`make generate` locally.
- [x] Non-trivial go.mod changes, e.g. adding new modules, are reviewed
by @DataDog/dd-trace-go-guild. Make sure all nested modules are up to
date by running `make fix-modules` locally.